version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mypgadmin}
      POSTGRES_DB: ${POSTGRES_DB:-betting_game}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./betting-game/backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./betting-game/backend
    environment:
      PG_HOST: postgres
      PG_USER: ${POSTGRES_USER:-postgres}
      PG_PASSWORD: ${POSTGRES_PASSWORD:-mypgadmin}
      PG_DATABASE: ${POSTGRES_DB:-betting_game}
      PG_PORT: 5432
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    build:
      context: ./betting-game/frontend
    environment:
      REACT_APP_API_URL: ${API_URL:-http://localhost:3001/api}
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres_data: 